f=open(r'C:\Users\Zhibek\Documents\PP2\summer\tsis4\2.py','r',encoding='utf-8')
data=f.read() 
import re

PatternName=re.compile(r'Филиал\sТОО\s\w+\s\w+')
PatternBin=re.compile(r'\d{12}')
PatternItemTitles=re.compile(r'\d+\.\n(.*)')
PatternItemCount=re.compile(r'(\d),\d{3}')
PatternItemPrice=re.compile(r'x\s([\d\s]+,\d+)')
PatternItemTotalPrice=re.compile(r'Стоимость\n([\d\s]+\,\d+)')
PatternDate=re.compile(r'\d{2}\.\d{2}\.\d{4}\s\d{2}\:\d{2}\:\d{2}')
PatternAddress=re.compile(r'г\.\s[\w\-]+\,\w+\,\s[\w\s]+\,\d+\,\s\w+\-\d')

Name=re.search(PatternName,data)
BIN=re.search(PatternBin,data)
Date=re.search(PatternDate,data)
Address=re.search(PatternAddress,data)
ItemTitles=re.findall(PatternItemTitles,data)
ItemCount=re.findall(PatternItemCount,data)
ItemPrices=re.findall(PatternItemPrice,data)
ItemTotalPrice=re.findall(PatternItemTotalPrice,data)

print('1.Name of the company-'+Name.group(0))
print('2.BIN number-'+BIN.group(0)+'\n')
for i in range(len(ItemTitles)):
    print('\t1.Title:'+ItemTitles[i])
    print('\t2.Count:'+ItemCount[i])
    print('\t3.Unit Price:'+ItemPrices[i])
    print('\t4.Total Price:'+ItemTotalPrice[i]+'\n')
print('4.Date-'+Date.group(0))
print('5.Address-'+Address.group(0))